[versions]
minecraft = "1.19"
quilt_mappings = "1.19+build.1"
quilt_loader = "0.17.6"
quilted_fabric_api = "2.0.0-alpha.1+0.55.3-1.19"
jythonmc = "1.0.2"

[libraries.minecraft]
module = "com.mojang:minecraft"

  [libraries.minecraft.version]
  ref = "minecraft"

[libraries.quilt_mappings]
module = "org.quiltmc:quilt-mappings"

  [libraries.quilt_mappings.version]
  ref = "quilt_mappings"

[libraries.quilt_loader]
module = "org.quiltmc:quilt-loader"

  [libraries.quilt_loader.version]
  ref = "quilt_loader"

[libraries.quilted_fabric_api]
module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api"

  [libraries.quilted_fabric_api.version]
  ref = "quilted_fabric_api"

[libraries.quilted_fabric_api_deprecated]
module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api-deprecated"

  [libraries.quilted_fabric_api_deprecated.version]
  ref = "quilted_fabric_api"

[libraries.jythonmc]
module = "com.enderzombi102:JythonMC"

  [libraries.jythonmc.version]
  ref = "jythonmc"

[bundles]
quilted_fabric_api = [ "quilted_fabric_api", "quilted_fabric_api_deprecated" ]

[plugins.quilt_loom]
id = "org.quiltmc.loom"
version = "0.12.+"

