name: Update Dependencies

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update Dependencies
        uses: RyanModDev/quilted-dependabot@v0

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.1.1
